/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author lenin
 */
public class FrmProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtIdProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(451, 425));
        setPreferredSize(new java.awt.Dimension(451, 425));
        setResizable(false);
        setSize(new java.awt.Dimension(451, 425));
        getContentPane().setLayout(null);

        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(40, 330, 80, 30);

        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(300, 330, 70, 30);

        txtIdProducto.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtIdProducto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtIdProducto.setBorder(null);
        txtIdProducto.setOpaque(false);
        getContentPane().add(txtIdProducto);
        txtIdProducto.setBounds(160, 80, 220, 20);

        txtNombre.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(160, 130, 220, 20);

        txtPrecioCompra.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtPrecioCompra.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPrecioCompra.setBorder(null);
        txtPrecioCompra.setOpaque(false);
        getContentPane().add(txtPrecioCompra);
        txtPrecioCompra.setBounds(190, 180, 80, 30);

        txtStock.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtStock.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtStock.setBorder(null);
        txtStock.setOpaque(false);
        getContentPane().add(txtStock);
        txtStock.setBounds(360, 180, 60, 30);

        txtPrecioVenta.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtPrecioVenta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPrecioVenta.setBorder(null);
        txtPrecioVenta.setOpaque(false);
        getContentPane().add(txtPrecioVenta);
        txtPrecioVenta.setBounds(230, 230, 120, 30);

        txtCantidad.setBackground(new java.awt.Color(255, 255, 255, 0)
        );
        txtCantidad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCantidad.setBorder(null);
        txtCantidad.setOpaque(false);
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(250, 280, 60, 30);

        lbFondo.setIcon(new javax.swing.ImageIcon("D:\\lenin\\Documents\\NetBeansProjects\\TiendaVideojuegos\\src\\Vista\\img\\FrmProductos.png")); // NOI18N
        lbFondo.setOpaque(true);
        getContentPane().add(lbFondo);
        lbFondo.setBounds(0, 0, 451, 425);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
